### ISSUE TITLE
Module build not working

### ISSUE THREAD

**Issue by gpoitch** [bustle/mobiledoc-dom-renderer#43]
Need to investigate further but trying to use 0.6.0 with webpack 2 fails because it tries to dynamically reference `babel-helpers`

**Comment by bantic** [comment]
@gdub22 Yeah, this is an issue with glimmer/build that I noticed. I am going to publish a patch release version with a quick fix as well as try to fix this upstream.

**Comment by gdub22** [comment]
@bantic great, thanks.  I'm also noticing my (development) app size severely bloated after the update.  Likely because of all the separate files + sourcemaps for each.  My understanding, and how I've been doing module builds, is that you still transpile and concatenate to 1 file, you just leave `export` / `export default` syntax intact.

**Comment by gpoitch** [comment]
Not sure if relevant anymore
